[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.147.0"
  NODE_VERSION = "20"
  GO_VERSION = "1.21"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL --baseURL /" 
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL --baseURL /"
[context.production]
[context.production.environment]
HUGO_ENV = "production"

